### PR TITLE
Add a .gitattributes file.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
For synchronizing the source code it is important to keep the line endings as-is.

### CODE REVIEW

**Comment by AArnott** [comment]
Why is it necessary? Don't we normalize line endings in both repos?

**Comment by KirillOsenkov** [comment]
I'd like Git here to store exactly what I want and I want to turn off internal conversion to LF. We've seen numerous issues in various Git and VS tooling around automatic line ending conversion.

**Comment by AArnott** [comment]
> We've seen numerous issues in various Git and VS tooling around automatic line ending conversion.

Like what? I've never seen a problem. Anytime a source file is LF on Windows it creates significant problems (e.g. Notepad.exe doesn't work) so this normalizing policy keeps things working. :)

**Comment by KirillOsenkov** [comment]
Don't use Notepad.exe ;)

**Comment by AArnott** [comment]
ya... I usually avoid it when I can. But sometimes, it's all you have.

**Pull request merged**
